name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          GM from KBS, I am GitHub Actions Bot! 👋 
          Thank you for opening your first issue on this repository.
          
          We appreciate your contribution and are here to help. Please provide detailed information about the issue you're facing or the improvement you'd like to suggest. The KBS community is eager to collaborate with you! If you are trying to solve the issue go through [installation guide](https://github.com/Swarnendu0123/kbs-website/blob/main/docs%2Finstallation.md).
          If you have any questions or need guidance, feel free to ask. Happy coding! 🚀
        pr-message: |
          Hi contributor! 👋 Thanks for submitting your first pull request to this repository.

          Your efforts are valued, and we're excited to review your changes. Make sure to include a descriptive title and details about your pull request. If you're unsure about anything, don't hesitate to ask for help.

          We encourage you to adhere to our contribution guidelines and coding standards. Your contributions make KBS community better! 🙌

          Happy coding!
